version: '3.8'

services:
  nextjs:
    image: node:latest
    container_name: nextjs
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: sh -c 'npm run build && npm run start'

  nginx:
    image: nginx:1.23-alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: certonly --nginx -d justin.ly
