services:
  nextjs:
    image: node:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: |
      npm run dev
