services:
  web:
    container_name: web
    image: node:latest
    ports:
      - '80:3000'
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: sh -c 'npm run build && npm run start'
